version: '2'
services:
  odcmapping:
    entrypoint: zsh
    build: .
    volumes:
      - ./analysis:/src
      - $SOURCEDATA:/sourcedata:ro
      - $DERIVATIVES:/derivatives
      - /tmp/workflow_folders:/workflow_folders
