version: '2'
services:
  odcmapping:
    entrypoint: zsh
    build: .
    volumes:
      - ./analysis:/src
      - $SOURCEDATA:/sourcedata
      - $DERIVATIVES:/derivatives
      - /tmp/workflow_folders:/workflow_folders
      - ./spynoza:/spynoza
      - ./crashdumps:/crashdumps
      - /home/hollander/git/nighres/nighres:/nighres/nighres
