version: '2'
services:
  odcmapping:
    entrypoint: zsh
    build: .
    volumes:
      - ./analysis:/src
      - $SOURCEDATA:/sourcedata/ds-odc
      - $DERIVATIVES:/derivatives
      - /tmp/workflow_folders:/workflow_folders
      - ./spynoza:/spynoza
      - ./crashdumps:/crashdumps
      - /home/hollander/git/nighres/nighres:/nighres/nighres
      - /home/hollander/git/fmriprep:/fmriprep
      - /home/hollander/.local/freesurfer/license.txt:/opt/freesurfer-6.0.1/license.txt
