global:
  screen:
    size: [2560, 1440]
    full_screen: False
    background_color: [-1, -1, -1]
    gamma_scale: [2.475,2.25,2.15]
    physical_screen_size: [58, 36]
    physical_screen_distance: 60
    max_lums: [24.52, 78.8, 10.19]
    wait_blanking: True
    mouse_visible: False
    screen_nr: 2
    framerate: 60

  stimuli:
    x_offset_left_eye: 0
    y_offset_left_eye: 0
    x_offset_right_eye: 0
    y_offset_right_eye: 0

    left_size: 10
    right_size: 10
       
  cross:
    linewidth: .1
    color: [1, -1, -1]

  rim:
    contrast: 0.5
    rim_ratio: 1.1
    n_parts: 16

  fixation:
    proportion: 0.05

  checker_cross:
    ratio_to_circle: 1.3
    n_sides: 32
    n_blocks: 4

  buttons:
    keys: ['a', 's', 'd', 'f']

  timing:
    stimulus_length: 12


