global:
  screen:
    size: [1600, 1200]
    full_screen: False
    background_color: [-1, -1, -1]
    gamma_scale: [2.475,2.25,2.15]
    physical_screen_size: [60, 34]
    physical_screen_distance: 50
    max_lums: [24.52, 78.8, 10.19]
    wait_blanking: True
    mouse_visible: False
    screen_nr: 2
  positions:
    x_offset_left_eye: 0
    y_offset_left_eye: 0
    x_offset_right_eye: 2
    y_offset_right_eye: 5

    left_size: 15
    scale_left_right: 1.02

